apiVersion: v1
kind: Service
metadata:
  name: {{ include "clearinghouse.fullname" . }}
  labels:
    {{- include "clearinghouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: connector
      protocol: TCP
      name: http
    - port: 8001
      targetPort: docapi
      protocol: TCP
      name: docapi
    - port: 8002
      targetPort: keyring
      protocol: TCP
      name: keyring
  selector:
    {{- include "clearinghouse.selectorLabels" . | nindent 4 }}
