apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata-broker-open-core.fullname" . }}
  labels:
    {{- include "metadata-broker-open-core.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
  {{- if $val}}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end}}
  {{- if .Values.fuseki.deploy }}
    SPARQL_URL: "http://{{ .Release.Name }}-broker-fuseki:3030/connectorData"
  {{- else }}
    SPARQL_URL: "{{ .Values.fuseki.address }}"
  {{- end }}