spring: 
  jackson:
    serialization: 
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource: 
    url: jdbc:postgresql://postgres:5432/postgresdb
    username: admin
    password: password@123

server:
  port: 9094
  servlet:
    context-path: /core     