server:
  port: 9095
  servlet:
    context-path: /provider

connector: 
  username: admin
  password: password
  provider:
    baseUrl: https://20.79.235.138:8080/api/
    
spring:
  data:
    mongodb:
      host: mongo 
      port: 27017
      database: csds-mongo