server:
  port: 9095
  servlet:
    context-path: /provider

spring:
   data: 
    mongodb:
      host: mongo 
      port: 27017
      database: csds-mongo
   servlet:
    multipart: 
     maxFileSize: 10MB
     maxRequestSize: 10MB