name: container-scan
on: push

jobs:
  security-scan:
    name: repo vunerability scan
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        run: |
          docker pull aquasec/trivy
          docker run aquasec/trivy --debug fs --format table .
        
        # uses: aquasecurity/trivy-action@master
        # with:
          # scan-type: 'fs'
          # ignore-unfixed: true
          # format: 'table'
          # # template: '@/contrib/sarif.tpl'
          # # output: 'trivy-results.sarif'
          # severity: 'CRITICAL'
          # exit-code: '1'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   if: always()
      #   with:
      #     sarif_file: 'trivy-results.sarif'

  config-scan:
    runs-on: ubuntu-latest
    name: IaC configuration scan
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@master
        
      - name: checkov iac scan
        if: always()
        run: |
          pip3 install checkov
          checkov --directory . -o sarif
          
      - name: Upload Checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'results.sarif'
      
