name: container-scan
on: push

jobs:
  security-scan:
    name: repo vunerability scan
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run trivy vulnerability scanner in repo mode
        run: |
          docker pull aquasec/trivy
          docker run --volume $(pwd):/data aquasec/trivy --debug fs --format template --template '@/contrib/sarif.tpl' --output /data/trivy-results.sarif --severity 'CRITICAL,HIGH' --exit-code 1 /data

      - name: upload trivy scan results to github security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  config-scan:
    runs-on: ubuntu-latest
    name: iac configuration scan
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@master
        
      - name: checkov iac scan
        if: always()
        run: |
          pip3 install checkov
          checkov --directory . -o sarif
          
      - name: upload checkov scan results to github security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'results.sarif'
