name: build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: scan repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-repo.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: upload repo scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-repo.sarif'

      - name: scan IaC configs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-iac.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: upload iac scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-iac.sarif'