name: container-scan
on: push

jobs:
  repo-scan:
    name: repo vunerability scan
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  iac-scan:
    name: iac configuration scan
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL'
          exit-code: '1'

  checkov-scan:
    runs-on: ubuntu-latest
    name: checkov-action
    continue-on-error: true
    steps:
      - name: checkout code
        uses: actions/checkout@master
        
      - name: checkov iac scan
        if: always()
        run: |
          pip3 install checkov
          checkov --directory . --framework terraform -o sarif
          
      - name: Upload Checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'results.sarif'
      