#name : CI
#
#on: 
#  workflow_dispatch:
#      tags:
#        description: 'Test scenario tags'
#        required: false 
#        type: boolean
##      environment:
##        description: 'Environment to run grafana'
##        type: environment
##        required: true 
#env:
#  CLUSTER_NAME: cxtsi-dev011-aks-services
#  CLUSTER_RESOURCE_GROUP: cxtsi-dev011-rg
#  NAMESPACE: monitoring
#  CONTAINER_REGISTRY: cxtsiacr
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    environment: Catena-X dev/int
#    steps:
#    - name: 'Checkout GitHub Action'
#      uses: actions/checkout@v2
#
#    - name: 'Login via Azure CLI'
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#    - name: 'Login to ACR'
#      uses: azure/docker-login@v1
#      with:
#        login-server: ${{ secrets.DEV_INT_ACR_SERVER }}
#        username: ${{ secrets.DEV_INT_ACR_USER }}
#        password: ${{ secrets.DEV_INT_ACR_PASSWORD }}
#
#    - name: 'Build the Docker image'
#      working-directory: grafana
#      run: |
#        docker build . -t ${{ secrets.DEV_INT_ACR_SERVER }}/dashboard:${{ github.sha }}
#        docker push ${{ secrets.DEV_INT_ACR_SERVER }}/dashboard:${{ github.sha }}
#    - name: 'Deploy to Azure App Service'
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'cxtsi-dev011-dashboard-appservice'
#        publish-profile: ${{ secrets.DEV011_DASHBOARD_WEBAPP_PUBLISH_PROFILE }}
#        images: ${{ secrets.DEV_INT_ACR_SERVER }}/dashboard:${{ github.sha }}
#
