name: PRS Deploy

on:
  push:
    branches:
      - main
    paths:
      - coreservices/partsrelationshipservice/**
      - .github/workflows/partsrelationshipservice-deploy.yml

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for resources'
        required: true
        default: 'dev'

concurrency: partsrelationshipservice-infra

jobs:
  configure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      # Default environment (overridden when run manually)
      ENVIRONMENT: dev
    steps:
      - uses: actions/checkout@v2
      - name: "Configure environment (manual run only)"
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - id: get-dataspace-partitions
        run: |
          set -euo pipefail # safe mode
          dataspace_partitions=$(jq -c .partitions cd/dataspace-partitions.json)
          echo "::set-output name=dataspace_partitions::$dataspace_partitions"
    outputs:
      dataspace_partitions: ${{ steps.get-dataspace-partitions.outputs.dataspace_partitions }}
      environment: ${{ env.ENVIRONMENT }}
      image_tag: ${{ github.run_id }}

  infra_common:
    needs:
    - configure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice/cd/terraform-common
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Terraform
        id: terraform
        run: ../run-terraform.sh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TERRAFORM_STATE_BLOB: mtpdc.${{ needs.configure.outputs.environment }}.tfstate
          TERRAFORM_VARS: ../environments/${{ needs.configure.outputs.environment }}.sh
    outputs:
      application_insights_name: ${{ steps.terraform.outputs.application_insights_name }}

  infra_connector_consumer:
    needs:
      - configure
      - infra_common
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build fake index of dataspace URLs"
        run: |
          echo '{}' > dev/local/dataspace-deployments.json

      - name: Run Terraform
        run: ../run-terraform.sh
        working-directory: coreservices/partsrelationshipservice/cd/terraform-connector-consumer
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TERRAFORM_STATE_BLOB: mtpdc.consumer.${{ needs.configure.outputs.environment }}.tfstate
          TERRAFORM_VARS: ../environments/${{ needs.configure.outputs.environment }}.sh
          TF_VAR_image_tag: ${{ needs.configure.outputs.image_tag }} # Image tag of connectors
          TF_VAR_application_insights_name: ${{ needs.infra_common.outputs.application_insights_name }}
